"""
Armada Movement Scorer

Armada (armed) or meia lua de costas is a 360° spinning kick delivered
with the outside edge of the foot. One of capoeira's most powerful kicks.

BIOMECHANICAL BASIS:
- Power comes from torque placed on hips from the spin
- Torso acts as a spring, propelling the leg into motion
- 270-360° rotation from initial ginga position
- Strike with outside edge of foot at head height

Sources:
- CapoeiraWiki technical analysis
- PMC5571909: Roundhouse kick biomechanics study
"""

from typing import List
from analyzer.movement_scorer import MovementScorer, AngleCriterion, create_criterion


class ArmadaScorer(MovementScorer):
    """
    Scores the Armada (Spinning Kick) movement.

    The armada is assessed on:
    1. Kicking leg extension - full extension at impact (155-180°)
    2. Support leg stability - bent for balance during spin (130-165°)
    3. Hip rotation - drives the kick power
    4. Spine alignment - relatively upright during rotation

    Based on biomechanical research (PMC5571909).
    """

    # ================================================================
    # CALIBRATED VALUES - Based on biomechanical research
    # PMC5571909: Knee at impact 15-43° flexion for roundhouse kicks
    # Capoeira armada aims for fuller extension
    # ================================================================

    # Kicking leg knee angle at impact (degrees)
    # Near-full extension for maximum reach and power
    IDEAL_KICK_KNEE_MIN = 155  # Near full extension
    IDEAL_KICK_KNEE_MAX = 180  # Full extension

    # Support leg knee angle (degrees)
    # Bent for stability during spin - research confirms this
    IDEAL_SUPPORT_KNEE_MIN = 130  # Good bend for stability
    IDEAL_SUPPORT_KNEE_MAX = 165  # Not locked

    # Hip angles (degrees)
    # Varies through the rotation phase
    IDEAL_HIP_ANGLE_MIN = 90   # During kick extension
    IDEAL_HIP_ANGLE_MAX = 170  # Before/after kick

    # Spine angle (degrees)
    # Should remain relatively upright during spin
    IDEAL_SPINE_MIN = 145  # Slight lean acceptable
    IDEAL_SPINE_MAX = 180  # Upright

    # Shoulder angle (degrees)
    # Arms help generate rotation momentum
    IDEAL_SHOULDER_MIN = 30   # Arms active
    IDEAL_SHOULDER_MAX = 120  # Extended for momentum

    def _setup(self):
        """Set up armada-specific scoring criteria."""
        self.movement_name = "Armada"
        self.movement_name_pt = "Armada"
        self.description = (
            "Armada is a 360° spinning kick delivered with the outside edge "
            "of the foot. The power comes from hip torque generated by the "
            "spin - the torso acts as a spring, propelling the leg. Targets "
            "the opponent's head or upper body."
        )

        self.criteria = [
            create_criterion(
                name="Kicking Leg Extension",
                angle_key="left_knee",
                ideal_min=self.IDEAL_KICK_KNEE_MIN,
                ideal_max=self.IDEAL_KICK_KNEE_MAX,
                weight=1.0,
                description="Near-full extension at impact (155-180°)"
            ),
            create_criterion(
                name="Support Leg Stability",
                angle_key="right_knee",
                ideal_min=self.IDEAL_SUPPORT_KNEE_MIN,
                ideal_max=self.IDEAL_SUPPORT_KNEE_MAX,
                weight=1.0,
                description="Bent for stability during spin (130-165°)"
            ),
            create_criterion(
                name="Kicking Hip Drive",
                angle_key="left_hip",
                ideal_min=self.IDEAL_HIP_ANGLE_MIN,
                ideal_max=self.IDEAL_HIP_ANGLE_MAX,
                weight=1.0,
                description="Hip drives the kick (90-170°)"
            ),
            create_criterion(
                name="Support Hip Position",
                angle_key="right_hip",
                ideal_min=self.IDEAL_HIP_ANGLE_MIN,
                ideal_max=self.IDEAL_HIP_ANGLE_MAX,
                weight=0.8,
                description="Hip rotation angle"
            ),
            create_criterion(
                name="Spine Alignment",
                angle_key="spine",
                ideal_min=self.IDEAL_SPINE_MIN,
                ideal_max=self.IDEAL_SPINE_MAX,
                weight=0.9,
                description="Upright during rotation (145-180°)"
            ),
            create_criterion(
                name="Left Arm Momentum",
                angle_key="left_shoulder",
                ideal_min=self.IDEAL_SHOULDER_MIN,
                ideal_max=self.IDEAL_SHOULDER_MAX,
                weight=0.6,
                description="Arms generate spin (30-120°)"
            ),
            create_criterion(
                name="Right Arm Momentum",
                angle_key="right_shoulder",
                ideal_min=self.IDEAL_SHOULDER_MIN,
                ideal_max=self.IDEAL_SHOULDER_MAX,
                weight=0.6,
                description="Arms generate spin (30-120°)"
            ),
        ]

        self.common_mistakes = [
            "Incomplete spin - not completing full 360° rotation",
            "Bent knee at impact - should be near-full extension (>155°)",
            "Locked support leg - should have bend (130-165°)",
            "Excessive forward lean during spin (spine <145°)",
            "Eyes not spotting target throughout rotation",
            "Arms passive - not generating rotation momentum",
            "Landing off balance after kick",
            "Kick too low - should target head height",
            "Telegraphing the spin - too much wind-up visible",
            "Slow rotation - lacking hip torque power",
        ]

    def get_calibration_guide(self) -> str:
        """Returns biomechanical reference for armada technique."""
        return """
        ARMADA BIOMECHANICAL REFERENCE
        ==============================

        CALIBRATED VALUES:
        - Kicking knee: 155-180° (near-full extension)
        - Support knee: 130-165° (bent for stability)
        - Hip angle: 90-170° (varies through rotation)
        - Spine: 145-180° (relatively upright)
        - Shoulders: 30-120° (active for momentum)

        FLAWLESS EXECUTION CRITERIA:
        1. Complete 360° rotation smoothly
        2. Full leg extension at impact point
        3. Eyes track target throughout spin
        4. Arms actively generate rotation
        5. Controlled landing back to ginga

        Source: PMC5571909 (Roundhouse kick biomechanics)
        """


def create_armada_scorer() -> ArmadaScorer:
    """Create and return an ArmadaScorer instance."""
    return ArmadaScorer()
